export const NAV = [
  { to:'/', label:'Dashboard', icon:'LayoutDashboard' },
  { to:'/tasks', label:'Tasks', icon:'ListTodo' },
  { to:'/landlords', label:'Landlords', icon:'UserRound' },
  { to:'/properties', label:'Properties', icon:'Home' },
  { to:'/tenants', label:'Tenants', icon:'Users' },
  { to:'/contracts', label:'Contracts', icon:'FileSignature' },
  { to:'/rent', label:'Rent', icon:'PoundSterling' },
  { to:'/deposits', label:'Deposits', icon:'ShieldCheck' },
  { to:'/repairs', label:'Repairs', icon:'Wrench' },
  { to:'/inspections', label:'Inspections', icon:'SearchCheck' },
  { to:'/inventories', label:'Inventories', icon:'ClipboardList' },
  { to:'/compliance', label:'Compliance', icon:'BadgeCheck' },
  { to:'/rent-smart-wales', label:'Rent Smart Wales', icon:'Landmark' },
  { to:'/contractors', label:'Contractors', icon:'HardHat' },
  { to:'/invoices', label:'Invoices', icon:'ReceiptText' },
  { to:'/expenses', label:'Expenses', icon:'CreditCard' },
  { to:'/accounting', label:'Accounting', icon:'ChartNoAxesCombined' },
  { to:'/documents', label:'Documents', icon:'FolderOpen' },
  { to:'/communications', label:'Communications', icon:'MessagesSquare' },
  { to:'/notices', label:'Notices', icon:'BellRing' },
  { to:'/reports', label:'Reports', icon:'FileChartColumn' },
  { to:'/settings', label:'Settings', icon:'Settings' }
]

const propertyOptions={source:'properties',label:'address_line1',secondary:'town'}
const tenantOptions={source:'tenants',label:'first_name',secondary:'surname'}
const landlordOptions={source:'landlords',label:'full_legal_name'}
const contractOptions={source:'contracts',label:'contract_number'}
const contractorOptions={source:'contractors',label:'name',secondary:'company'}

export const RESOURCE_FIELDS={
  tasks:[
    {name:'title',label:'What needs doing?',required:true},
    {name:'details',label:'Details / what to change or inspect',type:'textarea'},
    {name:'category',label:'Type',type:'select',options:['property_visit','maintenance','compliance','document','tenant_contact','rent','renovation','other']},
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions},
    {name:'tenant_id',label:'Contract-holder',type:'relationship',options:tenantOptions},
    {name:'contract_id',label:'Contract',type:'relationship',options:contractOptions},
    {name:'landlord_id',label:'Landlord',type:'relationship',options:landlordOptions},
    {name:'location',label:'Meeting point / access note'},
    {name:'due_date',label:'Date',type:'date',required:true},
    {name:'due_time',label:'Time',type:'time'},
    {name:'assigned_to',label:'Assigned to'},
    {name:'priority',label:'Priority',type:'select',options:['low','normal','high','urgent']},
    {name:'status',label:'Status',type:'select',options:['open','in_progress','waiting','completed','cancelled']},
    {name:'completion_date',label:'Completion date',type:'date'},
    {name:'completion_notes',label:'Outcome notes',type:'textarea'}
  ],
  landlords:[
    {name:'full_legal_name',label:'Full legal name',required:true},
    {name:'trading_name',label:'Trading / business name'},
    {name:'correspondence_address',label:'Correspondence address',type:'textarea'},
    {name:'phone',label:'Telephone'},{name:'email',label:'Email',type:'email'},
    {name:'company_number',label:'Companies House number'},{name:'tax_reference',label:'Tax / UTR'},
    {name:'bank_name',label:'Bank name'},{name:'bank_account_name',label:'Account name'},
    {name:'bank_sort_code',label:'Sort code'},{name:'bank_account_number',label:'Account number'},
    {name:'ownership_share',label:'Ownership %',type:'number'},
    {name:'solicitor_details',label:'Solicitor',type:'textarea'},
    {name:'accountant_details',label:'Accountant',type:'textarea'},
    {name:'emergency_contact',label:'Emergency contact',type:'textarea'},
    {name:'rsw_registration_number',label:'RSW registration number'},
    {name:'rsw_registration_start',label:'Registration start',type:'date'},
    {name:'rsw_registration_expiry',label:'Registration expiry',type:'date'},
    {name:'rsw_licence_number',label:'RSW licence number'},
    {name:'rsw_licence_type',label:'Licence type',type:'select',options:['Full Licence','Single Landlord','Joint Landlord','Agent-led']},
    {name:'rsw_licence_expiry',label:'Licence expiry',type:'date'},
    {name:'rsw_registration_certificate_file',label:'Upload registration certificate — any format',type:'file'},
    {name:'rsw_licence_certificate_file',label:'Upload landlord licence certificate — any format',type:'file'},
    {name:'training_completed',label:'Training completed'},
    {name:'cpd_notes',label:'CPD record',type:'textarea'},{name:'notes',label:'Notes',type:'textarea'}
  ],
  properties:[
    {name:'address_line1',label:'Address line 1',required:true},
    {name:'address_line2',label:'Address line 2'},{name:'town',label:'Town / city'},
    {name:'county',label:'County'},{name:'postcode',label:'Postcode'},
    {name:'local_authority',label:'Local authority'},
    {name:'property_type',label:'Property type'},
    {name:'bedrooms',label:'Bedrooms',type:'number'},{name:'bathrooms',label:'Bathrooms',type:'number'},
    {name:'max_occupants',label:'Max occupants',type:'number'},
    {name:'furnishing',label:'Furnishing',type:'select',options:['Unfurnished','Part furnished','Furnished']},
    {name:'construction_type',label:'Construction type'},{name:'year_built',label:'Year built',type:'number'},
    {name:'council_tax_band',label:'Council tax band'},
    {name:'additional_licence_info',label:'Selective / additional licensing',type:'textarea'},
    {name:'utility_gas_supplier',label:'Gas supplier'},
    {name:'utility_electricity_supplier',label:'Electricity supplier'},
    {name:'utility_water_supplier',label:'Water supplier'},
    {name:'parking',label:'Parking',type:'boolean'},{name:'garden',label:'Garden',type:'boolean'},{name:'garage',label:'Garage',type:'boolean'},
    {name:'keys_access',label:'Keys / access',type:'textarea'},
    {name:'landlord_id',label:'Landlord',type:'relationship',options:landlordOptions},
    {name:'purchase_date',label:'Purchase date',type:'date'},
    {name:'purchase_price',label:'Purchase price',type:'number'},
    {name:'mortgage_lender',label:'Mortgage lender'},{name:'mortgage_account',label:'Mortgage account'},
    {name:'mortgage_interest_rate',label:'Interest rate %',type:'number'},
    {name:'insurance_provider',label:'Insurance provider'},{name:'insurance_policy_number',label:'Policy number'},
    {name:'insurance_expiry',label:'Insurance expiry',type:'date'},
    {name:'status',label:'Status',type:'select',options:['occupied','vacant','notice','works','sold']},
    {name:'photo_url',label:'Photo URL'},{name:'floor_plan_url',label:'Floor plan URL'},
    {name:'photo_files',label:'Upload property photos / gallery files — any format',type:'files'},
    {name:'notes',label:'Notes',type:'textarea'}
  ],
  tenants:[
    {name:'title',label:'Title',type:'select',options:['Mr','Mrs','Miss','Ms','Dr','Prof','Mx']},
    {name:'first_name',label:'First name',required:true},{name:'middle_name',label:'Middle name'},{name:'surname',label:'Surname',required:true},
    {name:'date_of_birth',label:'Date of birth',type:'date'},{name:'current_address',label:'Current address',type:'textarea'},
    {name:'previous_address',label:'Previous address',type:'textarea'},{name:'mobile',label:'Mobile'},{name:'email',label:'Email',type:'email'},
    {name:'emergency_contact_name',label:'Emergency contact'},{name:'emergency_contact_relationship',label:'Relationship'},
    {name:'emergency_contact_phone',label:'Emergency phone'},
    {name:'guarantor_name',label:'Guarantor'},{name:'guarantor_address',label:'Guarantor address',type:'textarea'},
    {name:'guarantor_phone',label:'Guarantor phone'},{name:'guarantor_email',label:'Guarantor email'},
    {name:'tenant_reference',label:'Tenant reference'},{name:'occupants',label:'Occupants'},{name:'dependants',label:'Children / dependants'},
    {name:'pets',label:'Pets'},{name:'vehicles',label:'Vehicles'},
    {name:'application_date',label:'Application date',type:'date'},
    {name:'referencing_status',label:'Referencing status',type:'select',options:['not_started','in_progress','passed','failed']},
    {name:'reference_result',label:'Reference result'},{name:'previous_landlord_reference',label:'Previous landlord reference',type:'textarea'},
    {name:'employment_details',label:'Employment details',type:'textarea'},
    {name:'annual_income',label:'Annual income',type:'number'},
    {name:'credit_check_result',label:'Credit / reference check'},
    {name:'right_to_rent_check',label:'Right-to-occupy check',type:'date'},
    {name:'right_to_rent_result',label:'Right-to-occupy result'},
    {name:'id_document_url',label:'ID document URL'},{name:'notes',label:'Notes',type:'textarea'}
  ],
  contracts:[
    {name:'contract_number',label:'Contract number',required:true},
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions},
    {name:'tenant_id',label:'Contract-holder',type:'relationship',options:tenantOptions},
    {name:'landlord_id',label:'Landlord',type:'relationship',options:landlordOptions},
    {name:'start_date',label:'Start date',type:'date',required:true},
    {name:'occupation_date',label:'Occupation date',type:'date'},
    {name:'contract_type',label:'Contract type',type:'select',options:['periodic','fixed']},
    {name:'fixed_end_date',label:'Fixed end date',type:'date'},
    {name:'rent_amount',label:'Rent amount',type:'number',required:true},
    {name:'rent_frequency',label:'Rent frequency',type:'select',options:['weekly','fortnightly','monthly','quarterly']},
    {name:'rent_due_day',label:'Rent due day',type:'number'},
    {name:'deposit_amount_note',label:'Deposit note'},
    {name:'written_statement_sent',label:'Written statement sent',type:'date'},
    {name:'written_statement_signed',label:'Written statement signed',type:'date'},
    {name:'additional_terms',label:'Additional terms',type:'textarea'},
    {name:'pets_allowed',label:'Pets allowed',type:'boolean'},
    {name:'utilities_responsibility',label:'Utilities responsibility'},
    {name:'council_tax_responsibility',label:'Council tax responsibility'},
    {name:'garden_responsibility',label:'Garden responsibility'},
    {name:'repairs_responsibility',label:'Repairs responsibility'},
    {name:'status',label:'Status',type:'select',options:['draft','active','notice','ended']},
    {name:'end_date',label:'End date',type:'date'},
    {name:'termination_reason',label:'Termination reason',type:'textarea'},{name:'notes',label:'Notes',type:'textarea'}
  ],
  deposits:[
    {name:'contract_id',label:'Contract',type:'relationship',options:contractOptions},
    {name:'amount',label:'Deposit amount',type:'number',required:true},
    {name:'date_received',label:'Date received',type:'date'},
    {name:'scheme',label:'Scheme',type:'select',options:['DPS','TDS','MyDeposits','other']},
    {name:'scheme_reference',label:'Scheme reference'},
    {name:'date_protected',label:'Date protected',type:'date'},
    {name:'protection_deadline',label:'Protection deadline',type:'date'},
    {name:'prescribed_information_sent',label:'Prescribed information sent',type:'date'},
    {name:'acknowledgement_received',label:'Tenant acknowledgement',type:'boolean'},
    {name:'certificate_url',label:'Certificate URL'},
    {name:'deductions',label:'Deductions (JSON)',type:'json'},
    {name:'dispute_status',label:'Dispute status'},{name:'dispute_outcome',label:'Dispute outcome',type:'textarea'},
    {name:'returned_amount',label:'Returned amount',type:'number'},
    {name:'return_date',label:'Return date',type:'date'},
    {name:'status',label:'Status',type:'select',options:['received','protected','disputed','returned','unprotected']},
    {name:'notes',label:'Notes',type:'textarea'}
  ],
  compliance:[
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions,required:true},
    {name:'category',label:'Category',type:'select',required:true,options:['gas','eicr','epc','insurance','rsw_registration','rsw_licence','smoke_co_alarm','fire_detection_alarm_system','fire_risk','other']},
    {name:'title',label:'Title'},
    {name:'status',label:'Status',type:'select',options:['current','pending','remedial','expired','not_applicable']},
    {name:'inspection_date',label:'Inspection / issue date',type:'date',required:true},
    {name:'expiry_date',label:'Expiry / retest date',type:'date',required:true},
    {name:'next_review_date',label:'Next review date',type:'date'},
    {name:'provider_engineer',label:'Provider / engineer'},
    {name:'credential_number',label:'Engineer credential'},
    {name:'certificate_number',label:'Certificate number'},{name:'rating',label:'Rating / result'},
    {name:'findings',label:'Findings',type:'textarea'},
    {name:'control_measures',label:'Control measures',type:'textarea'},
    {name:'remedial_required',label:'Remedial required',type:'boolean'},
    {name:'remedial_completed_date',label:'Remedial completed',type:'date'},
    {name:'document_url',label:'Existing document URL'},
    {name:'evidence_file',label:'Upload certificate / evidence — any type',type:'file'},
    {name:'reminder_days',label:'Reminder days',type:'text'},
    {name:'notes',label:'Notes',type:'textarea'}
  ],
  devices:[
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions,required:true},
    {name:'device_type',label:'Device type',type:'select',required:true,options:['smoke_alarm','carbon_monoxide_alarm']},
    {name:'location',label:'Location',required:true},{name:'alarm_type',label:'Alarm type'},
    {name:'associated_appliance',label:'Associated appliance'},
    {name:'installation_date',label:'Installed',type:'date'},
    {name:'last_test_date',label:'Last tested',type:'date'},
    {name:'test_result',label:'Test result'},
    {name:'battery_status',label:'Battery status'},
    {name:'replacement_due',label:'Replacement due',type:'date'},
    {name:'contractor',label:'Contractor'},{name:'photo_url',label:'Photo URL'},{name:'notes',label:'Notes',type:'textarea'}
  ],
  contractors:[
    {name:'name',label:'Name',required:true},{name:'company',label:'Company'},{name:'address',label:'Address',type:'textarea'},
    {name:'phone',label:'Phone'},{name:'email',label:'Email'},{name:'trade',label:'Trade'},
    {name:'public_liability_insurer',label:'Public liability insurer'},
    {name:'public_liability_expiry',label:'Liability expiry',type:'date'},
    {name:'gas_safe_number',label:'Gas Safe number'},{name:'gas_safe_expiry',label:'Gas Safe expiry',type:'date'},
    {name:'electrical_qualification',label:'Electrical qualification'},
    {name:'other_qualifications',label:'Other qualifications',type:'textarea'},
    {name:'certificates_url',label:'Certificates URL'},
    {name:'preferred',label:'Preferred',type:'boolean'},
    {name:'hourly_rate',label:'Hourly rate',type:'number'},{name:'day_rate',label:'Day rate',type:'number'},
    {name:'bank_details',label:'Bank details'},{name:'score',label:'Score',type:'number'},{name:'notes',label:'Notes',type:'textarea'}
  ],
  repairs:[
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions,required:true},
    {name:'tenant_id',label:'Contract-holder',type:'relationship',options:tenantOptions},
    {name:'contractor_id',label:'Contractor',type:'relationship',options:contractorOptions},
    {name:'date_reported',label:'Date reported',type:'datetime-local',required:true},
    {name:'problem',label:'Problem',type:'textarea',required:true},
    {name:'category',label:'Category'},
    {name:'priority',label:'Priority',type:'select',options:['emergency','high','normal','low']},
    {name:'status',label:'Status',type:'select',options:['reported','assigned','quoted','approved','scheduled','in_progress','completed','invoiced','closed']},
    {name:'quote_amount',label:'Quote',type:'number'},{name:'approved_by',label:'Approved by'},
    {name:'appointment_at',label:'Appointment',type:'datetime-local'},
    {name:'access_arrangements',label:'Access arrangements',type:'textarea'},
    {name:'completed_date',label:'Completed',type:'date'},
    {name:'invoice_amount',label:'Invoice amount',type:'number'},
    {name:'invoice_url',label:'Invoice URL'},{name:'warranty_until',label:'Warranty until',type:'date'},
    {name:'follow_up_date',label:'Follow-up',type:'date'},
    {name:'tenant_notified',label:'Tenant notified',type:'boolean'},
    {name:'landlord_notified',label:'Landlord notified',type:'boolean'},
    {name:'evidence_files',label:'Upload quotes / invoices / photos — any format',type:'files'},
    {name:'photos',label:'Photos (JSON)',type:'json'},
    {name:'resolution_notes',label:'Resolution notes',type:'textarea'}
  ],
  inspections:[
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions,required:true},
    {name:'tenant_id',label:'Contract-holder',type:'relationship',options:tenantOptions},
    {name:'inspection_date',label:'Inspection date',type:'date',required:true},
    {name:'inspector',label:'Inspector'},
    {name:'general_condition',label:'General condition',type:'textarea'},
    {name:'damp_mould',label:'Damp / mould',type:'textarea'},
    {name:'windows_doors',label:'Windows / doors',type:'textarea'},
    {name:'heating',label:'Heating',type:'textarea'},
    {name:'plumbing',label:'Plumbing',type:'textarea'},
    {name:'electrical',label:'Electrical',type:'textarea'},
    {name:'smoke_alarms',label:'Smoke alarms',type:'textarea'},
    {name:'co_alarms',label:'CO alarms',type:'textarea'},
    {name:'garden_external',label:'Garden / external',type:'textarea'},
    {name:'repairs_required',label:'Repairs required',type:'textarea'},
    {name:'priority',label:'Priority',type:'select',options:['emergency','high','normal','low']},
    {name:'tenant_comments',label:'Tenant comments',type:'textarea'},
    {name:'follow_up_date',label:'Follow-up',type:'date'},
    {name:'report_url',label:'Existing report URL'},
    {name:'evidence_files',label:'Upload inspection report / photos — any format',type:'files'}
  ],
  inventories:[
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions,required:true},
    {name:'contract_id',label:'Contract',type:'relationship',options:contractOptions},
    {name:'inventory_type',label:'Type',type:'select',options:['check_in','check_out','interim']},
    {name:'inventory_date',label:'Inventory date',type:'date',required:true},
    {name:'inspector',label:'Inspector'},{name:'tenant_present',label:'Tenant present'},
    {name:'room_data',label:'Room-by-room data (JSON)',type:'json'},
    {name:'meter_readings',label:'Meter readings (JSON)',type:'json'},
    {name:'keys_count',label:'Keys',type:'number'},
    {name:'photos',label:'Photos (JSON)',type:'json'},
    {name:'tenant_acknowledgement',label:'Tenant acknowledgement',type:'boolean'},
    {name:'signed_document_url',label:'Signed inventory URL'},
    {name:'evidence_files',label:'Upload inventory / photos / signatures — any format',type:'files'},
    {name:'comparison_notes',label:'Check-in vs check-out',type:'textarea'},
    {name:'estimated_costs',label:'Estimated costs (JSON)',type:'json'}
  ],
  rent:[
    {name:'contract_id',label:'Contract',type:'relationship',options:contractOptions,required:true},
    {name:'due_date',label:'Due date',type:'date',required:true},
    {name:'period_start',label:'Period start',type:'date'},
    {name:'period_end',label:'Period end',type:'date'},
    {name:'amount_due',label:'Amount due',type:'number',required:true},
    {name:'amount_received',label:'Amount received',type:'number'},
    {name:'payment_date',label:'Payment date',type:'date'},
    {name:'payment_method',label:'Payment method'},
    {name:'payment_reference',label:'Reference'},
    {name:'allocation_notes',label:'Allocation notes',type:'textarea'},
    {name:'notes',label:'Notes',type:'textarea'}
  ],
  invoices:[
    {name:'invoice_number',label:'Invoice number'},
    {name:'invoice_type',label:'Type',type:'select',options:['management_fee','tenant_charge','contractor','maintenance','repair_recharge','deposit_statement','rent_statement','arrears_statement','landlord_monthly','landlord_annual','credit_note','refund','purchase','expense']},
    {name:'landlord_id',label:'Landlord',type:'relationship',options:landlordOptions},
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions},
    {name:'tenant_id',label:'Tenant',type:'relationship',options:tenantOptions},
    {name:'contractor_id',label:'Contractor',type:'relationship',options:contractorOptions},
    {name:'issue_date',label:'Issue date',type:'date'},
    {name:'due_date',label:'Due date (auto: 14 days)',type:'date'},
    {name:'customer_name',label:'Customer',required:true},{name:'customer_address',label:'Customer address',type:'textarea'},
    {name:'line_items',label:'Invoice lines',type:'invoice_lines'},
    {name:'amount_paid',label:'Amount paid',type:'number'},
    {name:'payment_date',label:'Payment date',type:'date'},
    {name:'payment_method',label:'Payment method'},{name:'payment_reference',label:'Payment reference'},
    {name:'bank_details',label:'Bank details',type:'textarea'},{name:'terms',label:'Terms'},
    {name:'notes',label:'Notes',type:'textarea'}
  ],
  expenses:[
    {name:'expense_date',label:'Expense date',type:'date',required:true},
    {name:'supplier',label:'Supplier'},{name:'category',label:'Category'},
    {name:'description',label:'Description',required:true},
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions},
    {name:'landlord_id',label:'Landlord',type:'relationship',options:landlordOptions},
    {name:'net_amount',label:'Net',type:'number'},{name:'vat_amount',label:'VAT',type:'number'},
    {name:'receipt_url',label:'Receipt URL'},{name:'payment_method',label:'Payment method'},
    {name:'evidence_files',label:'Upload receipt PDFs / photos — any format',type:'files'},
    {name:'paid_by',label:'Paid by'},{name:'rechargeable',label:'Rechargeable',type:'boolean'},
    {name:'tax_category',label:'Tax category'},
    {name:'deductible_assumption',label:'Tax treatment note',type:'textarea'},
    {name:'notes',label:'Notes',type:'textarea'}
  ],
  communications:[
    {name:'occurred_at',label:'Occurred at',type:'datetime-local'},
    {name:'direction',label:'Direction',type:'select',options:['incoming','outgoing','internal']},
    {name:'channel',label:'Channel',type:'select',options:['email','sms','letter','phone','whatsapp','portal','meeting','other']},
    {name:'subject',label:'Subject'},{name:'body',label:'Body',type:'textarea'},
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions},
    {name:'tenant_id',label:'Tenant',type:'relationship',options:tenantOptions},
    {name:'landlord_id',label:'Landlord',type:'relationship',options:landlordOptions},
    {name:'contractor_id',label:'Contractor',type:'relationship',options:contractorOptions},
    {name:'participants',label:'Participants'},{name:'attachment_url',label:'Attachment URL'},
    {name:'outcome',label:'Outcome',type:'textarea'}
  ],
  notices:[
    {name:'notice_type',label:'Notice type',required:true},
    {name:'property_id',label:'Property',type:'relationship',options:propertyOptions},
    {name:'tenant_id',label:'Tenant',type:'relationship',options:tenantOptions},
    {name:'contract_id',label:'Contract',type:'relationship',options:contractOptions},
    {name:'date_created',label:'Date created',type:'date'},
    {name:'date_served',label:'Date served',type:'date'},
    {name:'service_method',label:'Method'},
    {name:'recipient',label:'Recipient'},
    {name:'document_url',label:'Document URL'},{name:'proof_of_service',label:'Proof of service',type:'textarea'},
    {name:'response',label:'Response',type:'textarea'},
    {name:'deadline',label:'Deadline',type:'date'},
    {name:'status',label:'Status',type:'select',options:['draft','served','acknowledged','expired','withdrawn']},
    {name:'notes',label:'Notes',type:'textarea'}
  ]
}

export const TABLE_COLUMNS={
  tasks:['title','category','property_id','due_date','due_time','priority','status','assigned_to'],
  landlords:['full_legal_name','email','phone','rsw_registration_expiry','rsw_licence_expiry'],
  properties:['address_line1','town','postcode','property_type','bedrooms','status','insurance_expiry','document_count'],
  tenants:['first_name','surname','email','mobile','referencing_status'],
  contracts:['contract_number','property_id','tenant_id','start_date','rent_amount','rent_frequency','status'],
  deposits:['contract_id','amount','scheme','scheme_reference','date_protected','status'],
  compliance:['property_id','category','title','inspection_date','expiry_date','status','document_url'],
  devices:['property_id','device_type','location','last_test_date','replacement_due'],
  contractors:['name','company','trade','phone','public_liability_expiry','gas_safe_expiry'],
  repairs:['repair_number','property_id','problem','priority','status','date_reported','document_count'],
  inspections:['property_id','inspection_date','inspector','priority','document_count'],
  inventories:['property_id','inventory_type','inventory_date','inspector','tenant_acknowledgement','document_count'],
  rent:['contract_id','due_date','amount_due','amount_received','status','payment_method'],
  invoices:['invoice_number','invoice_type','customer_name','issue_date','total','amount_paid','payment_date','status'],
  expenses:['expense_date','supplier','category','description','net_amount','vat_amount','gross_amount','document_count'],
  documents:['title','folder','document_type','issue_date','expiry_date','original_name'],
  communications:['occurred_at','direction','channel','subject','participants'],
  notices:['notice_type','property_id','date_served','deadline','status'],
  reminders:['title','due_date','severity','message','acknowledged'],
  audit_logs:['occurred_at','actor_name','action','resource_table','summary']
}
